export type MetalCode = "gold" | "silver" | "platinum" | "palladium";

export type Product = {
  slug: string;
  name: string;
  metal: MetalCode;
  category: "Coin" | "Bar" | "Round" | "Bag";
  weightOz: number;
  purity: number;
  premium: number;
  image: string;
  featured?: boolean;
};

export const demoSpotPrices: Record<MetalCode, number> = {
  gold: 4625.4,
  silver: 58.72,
  platinum: 2184.9,
  palladium: 1742.6,
};

export const products: Product[] = [
  {
    slug: "1-oz-american-gold-eagle",
    name: "1 oz American Gold Eagle",
    metal: "gold",
    category: "Coin",
    weightOz: 1,
    purity: 1,
    premium: 185,
    image: "/products/gold-coin.svg",
    featured: true,
  },
  {
    slug: "half-oz-american-gold-eagle",
    name: "1/2 oz American Gold Eagle",
    metal: "gold",
    category: "Coin",
    weightOz: 0.5,
    purity: 1,
    premium: 125,
    image: "/products/gold-coin.svg",
  },
  {
    slug: "quarter-oz-american-gold-eagle",
    name: "1/4 oz American Gold Eagle",
    metal: "gold",
    category: "Coin",
    weightOz: 0.25,
    purity: 1,
    premium: 85,
    image: "/products/gold-coin.svg",
  },
  {
    slug: "tenth-oz-american-gold-eagle",
    name: "1/10 oz American Gold Eagle",
    metal: "gold",
    category: "Coin",
    weightOz: 0.1,
    purity: 1,
    premium: 55,
    image: "/products/gold-coin.svg",
  },
  {
    slug: "1-oz-american-gold-buffalo",
    name: "1 oz American Gold Buffalo",
    metal: "gold",
    category: "Coin",
    weightOz: 1,
    purity: 1,
    premium: 165,
    image: "/products/gold-coin.svg",
    featured: true,
  },
  {
    slug: "1-oz-canadian-gold-maple-leaf",
    name: "1 oz Canadian Gold Maple Leaf",
    metal: "gold",
    category: "Coin",
    weightOz: 1,
    purity: 0.9999,
    premium: 110,
    image: "/products/gold-coin.svg",
  },
  {
    slug: "1-oz-south-african-krugerrand",
    name: "1 oz South African Krugerrand",
    metal: "gold",
    category: "Coin",
    weightOz: 1,
    purity: 1,
    premium: 105,
    image: "/products/gold-coin.svg",
  },
  {
    slug: "1-oz-gold-bar",
    name: "1 oz Gold Bar",
    metal: "gold",
    category: "Bar",
    weightOz: 1,
    purity: 0.9999,
    premium: 79,
    image: "/products/gold-bar.svg",
    featured: true,
  },
  {
    slug: "10-gram-gold-bar",
    name: "10 gram Gold Bar",
    metal: "gold",
    category: "Bar",
    weightOz: 0.321507,
    purity: 0.9999,
    premium: 45,
    image: "/products/gold-bar.svg",
  },
  {
    slug: "5-gram-gold-bar",
    name: "5 gram Gold Bar",
    metal: "gold",
    category: "Bar",
    weightOz: 0.160754,
    purity: 0.9999,
    premium: 32,
    image: "/products/gold-bar.svg",
  },
  {
    slug: "1-gram-gold-bar",
    name: "1 gram Gold Bar",
    metal: "gold",
    category: "Bar",
    weightOz: 0.0321507,
    purity: 0.9999,
    premium: 18,
    image: "/products/gold-bar.svg",
  },
  {
    slug: "1-oz-american-silver-eagle",
    name: "1 oz American Silver Eagle",
    metal: "silver",
    category: "Coin",
    weightOz: 1,
    purity: 1,
    premium: 12.5,
    image: "/products/silver-coin.svg",
    featured: true,
  },
  {
    slug: "1-oz-canadian-silver-maple-leaf",
    name: "1 oz Canadian Silver Maple Leaf",
    metal: "silver",
    category: "Coin",
    weightOz: 1,
    purity: 0.9999,
    premium: 6.5,
    image: "/products/silver-coin.svg",
  },
  {
    slug: "1-oz-silver-britannia",
    name: "1 oz Silver Britannia",
    metal: "silver",
    category: "Coin",
    weightOz: 1,
    purity: 0.999,
    premium: 5.75,
    image: "/products/silver-coin.svg",
  },
  {
    slug: "1-oz-silver-round",
    name: "1 oz Silver Round",
    metal: "silver",
    category: "Round",
    weightOz: 1,
    purity: 1,
    premium: 3.25,
    image: "/products/silver-coin.svg",
    featured: true,
  },
  {
    slug: "1-oz-silver-bar",
    name: "1 oz Silver Bar",
    metal: "silver",
    category: "Bar",
    weightOz: 1,
    purity: 0.999,
    premium: 3.75,
    image: "/products/silver-bar.svg",
  },
  {
    slug: "5-oz-silver-bar",
    name: "5 oz Silver Bar",
    metal: "silver",
    category: "Bar",
    weightOz: 5,
    purity: 0.999,
    premium: 17,
    image: "/products/silver-bar.svg",
  },
  {
    slug: "10-oz-silver-bar",
    name: "10 oz Silver Bar",
    metal: "silver",
    category: "Bar",
    weightOz: 10,
    purity: 0.999,
    premium: 28,
    image: "/products/silver-bar.svg",
    featured: true,
  },
  {
    slug: "kilo-silver-bar",
    name: "1 Kilo Silver Bar",
    metal: "silver",
    category: "Bar",
    weightOz: 32.1507,
    purity: 0.999,
    premium: 75,
    image: "/products/silver-bar.svg",
  },
  {
    slug: "100-oz-silver-bar",
    name: "100 oz Silver Bar",
    metal: "silver",
    category: "Bar",
    weightOz: 100,
    purity: 0.999,
    premium: 190,
    image: "/products/silver-bar.svg",
  },
  {
    slug: "10-face-value-90-percent-silver",
    name: "$10 Face Value 90% Silver Coins",
    metal: "silver",
    category: "Bag",
    weightOz: 7.15,
    purity: 1,
    premium: 35,
    image: "/products/silver-coin.svg",
  },
  {
    slug: "1-oz-american-platinum-eagle",
    name: "1 oz American Platinum Eagle",
    metal: "platinum",
    category: "Coin",
    weightOz: 1,
    purity: 0.9995,
    premium: 145,
    image: "/products/platinum-bar.svg",
    featured: true,
  },
  {
    slug: "1-oz-platinum-maple-leaf",
    name: "1 oz Platinum Maple Leaf",
    metal: "platinum",
    category: "Coin",
    weightOz: 1,
    purity: 0.9995,
    premium: 125,
    image: "/products/platinum-bar.svg",
  },
  {
    slug: "1-oz-platinum-bar",
    name: "1 oz Platinum Bar",
    metal: "platinum",
    category: "Bar",
    weightOz: 1,
    purity: 0.9995,
    premium: 110,
    image: "/products/platinum-bar.svg",
    featured: true,
  },
  {
    slug: "1-oz-palladium-maple-leaf",
    name: "1 oz Palladium Maple Leaf",
    metal: "palladium",
    category: "Coin",
    weightOz: 1,
    purity: 0.9995,
    premium: 155,
    image: "/products/palladium-bar.svg",
  },
  {
    slug: "1-oz-palladium-bar",
    name: "1 oz Palladium Bar",
    metal: "palladium",
    category: "Bar",
    weightOz: 1,
    purity: 0.9995,
    premium: 135,
    image: "/products/palladium-bar.svg",
    featured: true,
  },
];

export function calculateProductPrice(product: Product, spot: number) {
  return spot * product.weightOz * product.purity + product.premium;
}

export function formatCurrency(value: number) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
  }).format(value);
}

export const metalLabels: Record<MetalCode, string> = {
  gold: "Gold",
  silver: "Silver",
  platinum: "Platinum",
  palladium: "Palladium",
};
